// Generated banner configurations. Windows rotate roughly every three
// weeks from late September 2026 (after the hand-authored launch banners).
// Rates are display copies of the standard core rate plan unless noted.
module.exports = {
  list: [
    // ------------------------- Featured rotation --------------------------
    { id: 'feat_meadow_veterans', name: 'Meadow Veterans', kind: 'featured',
      desc: 'Sir Reginald and Grandpa Oakbeard: the frontline that never dries out and never hurries.',
      featured: ['water_reginald', 'nature_oakbeard'], window: ['2026-09-28T00:00:00Z', '2026-10-19T00:00:00Z'] },
    { id: 'feat_disco_dawn', name: 'Disco Dawn', kind: 'featured',
      desc: 'Disco Oracle Yolanda saw this banner coming. It was, of course, a Friday.',
      featured: ['light_yolanda', 'fire_cindra'], window: ['2026-10-19T00:00:00Z', '2026-11-09T00:00:00Z'] },
    { id: 'feat_two_swords', name: 'Two Swords, One Banner', kind: 'featured',
      desc: 'Edgelord Kevin II and Admiral Bathtub. One broods. One floats. Both carry.',
      featured: ['dark_kevin2', 'water_bathtub'], window: ['2026-11-09T00:00:00Z', '2026-11-30T00:00:00Z'] },
    { id: 'feat_garden_party', name: 'Garden Party (Armed)', kind: 'featured',
      desc: 'Barbara Thornwood and Queen Cindra host. RSVP is mandatory and so is the violence.',
      featured: ['nature_barbara', 'fire_cindra'], window: ['2026-11-30T00:00:00Z', '2026-12-21T00:00:00Z'] },
    { id: 'feat_midwinter_keys', name: 'Midwinter Keys', kind: 'featured',
      desc: 'Saint Brightbeard finds your keys, your hope, and the featured 5★ slot.',
      featured: ['light_brightbeard', 'dark_bedtime'], window: ['2026-12-21T00:00:00Z', '2027-01-11T00:00:00Z'] },
    { id: 'feat_new_year_gains', name: 'New Year, New Gains', kind: 'featured',
      desc: 'Chad Emberstorm\'s resolution: everyone gets swole. Including you. Especially you.',
      featured: ['fire_chad', 'water_reginald'], window: ['2027-01-11T00:00:00Z', '2027-02-01T00:00:00Z'] },
    { id: 'feat_nap_appreciation', name: 'Nap Appreciation Week', kind: 'featured',
      desc: 'Baron Von Bedtime declares a realm-wide lie-down. Attendance horizontal.',
      featured: ['dark_bedtime', 'nature_oakbeard'], window: ['2027-02-01T00:00:00Z', '2027-02-22T00:00:00Z'] },
    { id: 'feat_spring_tide', name: 'Spring Tide', kind: 'featured',
      desc: 'Admiral Bathtub leads the spring flotilla. All ducks on deck.',
      featured: ['water_bathtub', 'nature_barbara'], window: ['2027-02-22T00:00:00Z', '2027-03-15T00:00:00Z'] },
    { id: 'feat_double_royalty', name: 'A Very Royal Banner', kind: 'featured',
      desc: 'Queen Cindra and Baron Von Bedtime. Two crowns, zero shared agenda.',
      featured: ['fire_cindra', 'dark_bedtime'], window: ['2027-03-15T00:00:00Z', '2027-04-05T00:00:00Z'] },
    { id: 'feat_lights_out', name: 'Lights Out', kind: 'featured',
      desc: 'Yolanda and Kevin II: the brightest light, the edgiest dark, one confusing playlist.',
      featured: ['light_yolanda', 'dark_kevin2'], window: ['2027-04-05T00:00:00Z', '2027-04-26T00:00:00Z'] },
    { id: 'feat_old_growth', name: 'Old Growth Festival', kind: 'featured',
      desc: 'Grandpa Oakbeard\'s birthday (est. age: 4,000). Gifts accepted in summons.',
      featured: ['nature_oakbeard', 'light_brightbeard'], window: ['2027-04-26T00:00:00Z', '2027-05-17T00:00:00Z'] },
    { id: 'feat_moist_order', name: 'Rites of the Order of Moist', kind: 'featured',
      desc: 'Sir Reginald\'s knighting anniversary. The ceremony is damp and DEEPLY moving.',
      featured: ['water_reginald', 'light_brightbeard'], window: ['2027-05-17T00:00:00Z', '2027-06-07T00:00:00Z'] },

    // ------------------------- Faction banners ----------------------------
    { id: 'fac_guild_gains', name: 'Guild of Gains Recruitment', kind: 'featured',
      desc: 'Fire-forward fitness fanatics. Cardio optional, courage mandatory.',
      featured: ['fire_chad'], poolTags: ['Guild of Gains'],
      guarantee: '10-pulls guarantee a Guild of Gains member.', window: ['2026-10-05T00:00:00Z', '2026-10-26T00:00:00Z'] },
    { id: 'fac_order_moist', name: 'Order of Moist Enlistment', kind: 'featured',
      desc: 'Take the damp vow. Towels forbidden.',
      featured: ['water_reginald'], poolTags: ['Order of Moist'],
      guarantee: '10-pulls guarantee an Order of Moist member.', window: ['2026-11-02T00:00:00Z', '2026-11-23T00:00:00Z'] },
    { id: 'fac_root_authority', name: 'Root Authority Hiring Drive', kind: 'featured',
      desc: 'The forest is unionizing and it needs organizers.',
      featured: ['nature_barbara'], poolTags: ['Root Authority'],
      guarantee: '10-pulls guarantee a Root Authority member.', window: ['2026-11-30T00:00:00Z', '2026-12-21T00:00:00Z'] },
    { id: 'fac_bright_bureau', name: 'Bright Bureau Open House', kind: 'featured',
      desc: 'The department of Light. Lost items found while you wait.',
      featured: ['light_brightbeard'], poolTags: ['Bright Bureau'],
      guarantee: '10-pulls guarantee a Bright Bureau member.', window: ['2027-01-04T00:00:00Z', '2027-01-25T00:00:00Z'] },
    { id: 'fac_nap_dynasty', name: 'Nap Dynasty Census', kind: 'featured',
      desc: 'The sleepiest royal line in history is counting subjects. Slowly.',
      featured: ['dark_bedtime'], poolTags: ['Nap Dynasty'],
      guarantee: '10-pulls guarantee a Nap Dynasty member.', window: ['2027-02-01T00:00:00Z', '2027-02-22T00:00:00Z'] },

    // ------------------------- Gather-In rotations ------------------------
    { id: 'gatherin_glimmer_r3', name: 'Glimmerdale Gather-In: Third Rotation', kind: 'gatherIn',
      desc: 'The steps return with Barbara Thornwood. Final step guarantees a 5★.',
      featured: ['nature_barbara'], rotationIndex: 1,
      rates: { featuredShareOfFiveStar: 60 },
      guarantee: 'Final 10-character step guarantees a 5★ with boosted Barbara odds.',
      steps: [
        { gemCost: 50, pullCount: 1, guarantee: '' }, { gemCost: 100, pullCount: 2, guarantee: '' },
        { gemCost: 150, pullCount: 3, guarantee: '' }, { gemCost: 250, pullCount: 4, guarantee: '' },
        { gemCost: 400, pullCount: 5, guarantee: '4★ guaranteed' }, { gemCost: 600, pullCount: 6, guarantee: '' },
        { gemCost: 900, pullCount: 8, guarantee: '4★ guaranteed' }, { gemCost: 1500, pullCount: 10, guarantee: '5★ GUARANTEED' } ],
      window: ['2026-09-21T00:00:00Z', '2026-10-12T00:00:00Z'] },
    { id: 'gatherin_glimmer_r4', name: 'Glimmerdale Gather-In: Fourth Rotation', kind: 'gatherIn',
      desc: 'Rotation four guarantees the featured 5★: Disco Oracle Yolanda.',
      featured: ['light_yolanda'], rotationIndex: 2,
      rates: { featuredShareOfFiveStar: 60 },
      guarantee: 'Final 10-character step guarantees the featured 5★: Yolanda.',
      steps: [
        { gemCost: 50, pullCount: 1, guarantee: '' }, { gemCost: 100, pullCount: 2, guarantee: '' },
        { gemCost: 150, pullCount: 3, guarantee: '' }, { gemCost: 250, pullCount: 4, guarantee: '' },
        { gemCost: 400, pullCount: 5, guarantee: '4★ guaranteed' }, { gemCost: 600, pullCount: 6, guarantee: '' },
        { gemCost: 900, pullCount: 8, guarantee: '4★ guaranteed' }, { gemCost: 1500, pullCount: 10, guarantee: 'FEATURED 5★ GUARANTEED' } ],
      window: ['2026-10-12T00:00:00Z', '2026-11-02T00:00:00Z'] },
    { id: 'gatherin_glimmer_r5', name: 'Glimmerdale Gather-In: Fifth Rotation', kind: 'gatherIn',
      desc: 'Rotation five features Chad Emberstorm. The steps ARE the workout.',
      featured: ['fire_chad'], rotationIndex: 1,
      rates: { featuredShareOfFiveStar: 60 },
      guarantee: 'Final 10-character step guarantees a 5★ with boosted Chad odds.',
      steps: [
        { gemCost: 50, pullCount: 1, guarantee: '' }, { gemCost: 100, pullCount: 2, guarantee: '' },
        { gemCost: 150, pullCount: 3, guarantee: '' }, { gemCost: 250, pullCount: 4, guarantee: '' },
        { gemCost: 400, pullCount: 5, guarantee: '4★ guaranteed' }, { gemCost: 600, pullCount: 6, guarantee: '' },
        { gemCost: 900, pullCount: 8, guarantee: '4★ guaranteed' }, { gemCost: 1500, pullCount: 10, guarantee: '5★ GUARANTEED' } ],
      window: ['2026-11-02T00:00:00Z', '2026-11-23T00:00:00Z'] },
    { id: 'gatherin_glimmer_r6', name: 'Glimmerdale Gather-In: Sixth Rotation', kind: 'gatherIn',
      desc: 'Rotation six guarantees the featured 5★: Edgelord Kevin II. He asked us to say it louder.',
      featured: ['dark_kevin2'], rotationIndex: 2,
      rates: { featuredShareOfFiveStar: 60 },
      guarantee: 'Final 10-character step guarantees the featured 5★: EDGELORD KEVIN II.',
      steps: [
        { gemCost: 50, pullCount: 1, guarantee: '' }, { gemCost: 100, pullCount: 2, guarantee: '' },
        { gemCost: 150, pullCount: 3, guarantee: '' }, { gemCost: 250, pullCount: 4, guarantee: '' },
        { gemCost: 400, pullCount: 5, guarantee: '4★ guaranteed' }, { gemCost: 600, pullCount: 6, guarantee: '' },
        { gemCost: 900, pullCount: 8, guarantee: '4★ guaranteed' }, { gemCost: 1500, pullCount: 10, guarantee: 'FEATURED 5★ GUARANTEED' } ],
      window: ['2026-11-23T00:00:00Z', '2026-12-14T00:00:00Z'] },

    // --------------------------- Step-Up banners --------------------------
    { id: 'stepup_object_lesson', name: 'Object Lesson Step-Up', kind: 'stepUp',
      desc: 'Sentient objects only: rocks, cups, socks, stoves. They have feelings AND stat lines.',
      featured: [], poolTags: ['Object'],
      rates: { fiveStar: 0, fourStar: 22, threeStar: 40, twoStar: 24, oneStar: 14, featuredShareOfFiveStar: 0 },
      guarantee: 'Object-only pool. Step 3 guarantees a 4★ Object.',
      steps: [
        { gemCost: 80, pullCount: 1, guarantee: '' },
        { gemCost: 240, pullCount: 3, guarantee: '' },
        { gemCost: 560, pullCount: 6, guarantee: '4★ guaranteed' },
        { gemCost: 1000, pullCount: 10, guarantee: 'Best available guaranteed' } ],
      window: ['2026-10-01T00:00:00Z', '2026-10-15T00:00:00Z'] },
    { id: 'stepup_union_drive', name: 'Union Drive Step-Up', kind: 'stepUp',
      desc: 'Solidarity summons. Union members at negotiated rates.',
      featured: [], poolTags: ['Union', 'Mercenary'],
      rates: { fiveStar: 0, fourStar: 20, threeStar: 45, twoStar: 22, oneStar: 13, featuredShareOfFiveStar: 0 },
      guarantee: 'Union pool. Step 4 guarantees the best available member.',
      steps: [
        { gemCost: 90, pullCount: 1, guarantee: '' },
        { gemCost: 270, pullCount: 3, guarantee: '' },
        { gemCost: 630, pullCount: 6, guarantee: '4★ guaranteed' },
        { gemCost: 1200, pullCount: 10, guarantee: 'Best available guaranteed' } ],
      window: ['2026-12-01T00:00:00Z', '2026-12-15T00:00:00Z'] },
    { id: 'stepup_royal_treatment', name: 'Royal Treatment Step-Up', kind: 'stepUp',
      desc: 'Royalty and Knights at escalating pomp. Trumpets included at step 3.',
      featured: ['fire_cindra'], poolTags: ['Royalty', 'Knight'],
      rates: { fiveStar: 6, fourStar: 18, threeStar: 40, twoStar: 22, oneStar: 14, featuredShareOfFiveStar: 50 },
      guarantee: 'Step 4 guarantees a 5★ Royal or Knight.',
      steps: [
        { gemCost: 120, pullCount: 1, guarantee: '' },
        { gemCost: 360, pullCount: 3, guarantee: '' },
        { gemCost: 800, pullCount: 6, guarantee: '4★ guaranteed' },
        { gemCost: 1500, pullCount: 10, guarantee: '5★ GUARANTEED' } ],
      window: ['2027-01-15T00:00:00Z', '2027-02-01T00:00:00Z'] },

    // --------------------------- Seasonal banners -------------------------
    { id: 'seasonal_spooky', name: 'The Spooky Season Banner', kind: 'featured',
      desc: 'Dark and Mystery units at their most powerful. The Ominous Sock is watching.',
      featured: ['dark_bedtime', 'dark_kevin2'], poolTags: ['Nap Dynasty', 'Mystery', 'Object', 'Bureau'],
      guarantee: '10-pulls always contain at least one 4★.', window: ['2026-10-24T00:00:00Z', '2026-11-02T00:00:00Z'] },
    { id: 'seasonal_harvest', name: 'The Great Harvest Banner', kind: 'featured',
      desc: 'Nature celebrates the harvest. The Aggressive Shrub celebrates aggressively.',
      featured: ['nature_oakbeard', 'nature_barbara'], poolTags: ['Root Authority', 'Elemental', 'Beast', 'Union'],
      guarantee: '10-pulls always contain at least one 4★.', window: ['2026-11-20T00:00:00Z', '2026-11-30T00:00:00Z'] },
    { id: 'seasonal_midwinter', name: 'Midwinter Lights Banner', kind: 'featured',
      desc: 'Light units shine longest on the longest night.',
      featured: ['light_brightbeard', 'light_yolanda'], poolTags: ['Bright Bureau', 'Human', 'Beast', 'Object'],
      guarantee: '10-pulls always contain at least one 4★.', window: ['2026-12-18T00:00:00Z', '2027-01-01T00:00:00Z'] },
    { id: 'seasonal_lunar_new_year', name: 'Lunar Cooperative New Year', kind: 'featured',
      desc: 'The moon rabbits\' first new year as owners. Rice cakes and rate-ups for all.',
      featured: ['water_bathtub', 'fire_cindra'],
      guarantee: '10-pulls always contain at least one 4★.', window: ['2027-02-05T00:00:00Z', '2027-02-19T00:00:00Z'] },

    // ------------------------- Wave 2 banners -----------------------------
    { id: 'fac_meadow_watch', name: 'The Meadow Watch Musters', kind: 'featured',
      desc: 'Captain Bramblebeard and Grandma Cinders recruit for the meadow\'s volunteer defense force. Somebody has to.',
      featured: ['nature_bramblebeard', 'fire_grandma_cinders'], poolTags: ['Meadow Watch'],
      guarantee: '10-pulls guarantee a Meadow Watch member.',
      window: ['2026-09-14T00:00:00Z', '2026-10-05T00:00:00Z'] },
    { id: 'feat_new_blood', name: 'New Blood: Crowns and Verdicts', kind: 'featured',
      desc: 'Her Dampness steps out of the puddle. Judge Lumen calls the court to order. The roster grows.',
      featured: ['water_puddle_queen', 'light_judge_lumen'],
      guarantee: '10-pulls always contain at least one 4★. Featured units take half of all 5★ results.',
      window: ['2026-10-26T00:00:00Z', '2026-11-16T00:00:00Z'] },
    { id: 'feat_void_hospitality', name: 'Void Hospitality', kind: 'featured',
      desc: 'Auntie Umbra opens the void for guests. Dinner is served. Attendance is not optional.',
      featured: ['dark_auntie_umbra', 'dark_bedtime'],
      guarantee: '10-pulls always contain at least one 4★. Featured units take half of all 5★ results.',
      window: ['2026-12-07T00:00:00Z', '2026-12-28T00:00:00Z'] },

    // ------------------------- Special banners ----------------------------
    { id: 'newplayer_first_steps', name: 'First Steps Summon', kind: 'stepUp',
      desc: 'A one-time welcome for new adventurers. Two discounted steps, then you\'re one of us.',
      featured: ['water_reginald'], permanent: true,
      guarantee: 'One-time steps: step 1 guarantees a 4★, step 2 guarantees a 5★.',
      steps: [
        { gemCost: 750, pullCount: 10, guarantee: '4★ guaranteed (half price)' },
        { gemCost: 1500, pullCount: 10, guarantee: '5★ GUARANTEED' } ] },
    { id: 'revival_hall_of_legends', name: 'Hall of Legends Revival', kind: 'featured',
      desc: 'Every previously-featured 5★, back for one encore. The nostalgia is complimentary.',
      featured: ['fire_chad', 'nature_barbara', 'dark_bedtime', 'light_brightbeard'],
      rates: { featuredShareOfFiveStar: 80 },
      guarantee: '10-pulls always contain at least one 4★. Featured legends take 80% of 5★ results.',
      window: ['2027-03-01T00:00:00Z', '2027-03-15T00:00:00Z'] },
    { id: 'villain_appreciation', name: 'Department of Doom Appreciation Week', kind: 'featured',
      desc: 'Official merchandise of the defeated. The packs file a complaint when torn. Dark and Bureau units boosted.',
      featured: ['dark_kevin2', 'dark_bedtime'], poolTags: ['Nap Dynasty', 'Bureau', 'Mystery', 'Object', 'Mercenary'],
      guarantee: '10-pulls always contain at least one 4★.',
      window: ['2027-03-20T00:00:00Z', '2027-03-27T00:00:00Z'] },
  ],
};
