// Generated event configurations. Enemy pools reference ids from the
// hand-authored enemy files and the generated chapter enemy files.
module.exports = {
  list: [
    // --------------------------- Event chapters ---------------------------
    { id: 'ev_pastry_uprising', name: 'The Pastry Uprising', kind: 'eventChapter',
      desc: 'The Great Dessert rises. Literally. Someone left the proofing spell on overnight.',
      theme: 'dessert_event', tokenId: 'sprinkle_token', stageCount: 8, scale: 1.1, bossScale: 1.2,
      enemyPool: ['rogue_scone', 'custard_elemental', 'churro_cactus', 'gelato_golem', 'biscotti_bandit', 'meringue_wisp', 'boss_tiramisu'],
      boss: 'boss_grand_gateau', clearTitle: 'Cake Appreciator',
      stageNames: ['The Dough Also Rises', 'Crust Uprising', 'Sconehenge', 'The Filling Front', 'TIRAMISU STRIKES BACK', 'Glaze of Glory', 'The Icing Line', 'GATEAU: ROUND TWO'],
      rewardTableId: 'rt_pastry', window: ['2026-09-10T00:00:00Z', '2026-09-24T00:00:00Z'],
      rewardTable: [
        { itemId: 'sprinkle_token', count: 15, weight: 50 }, { itemId: 'gold', count: 3000, weight: 25 },
        { itemId: 'gems', count: 20, weight: 15 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_moon_rent_strike', name: 'The Moon Rent Strike', kind: 'eventChapter',
      desc: 'Before the revolution, there was the rent strike. Stand with the rabbits.',
      theme: 'moon_event', tokenId: 'ricecake_token', stageCount: 8, scale: 1.6, bossScale: 1.4,
      enemyPool: ['moon_rabbit', 'crater_hermit', 'dust_bunny', 'tide_manager', 'cheese_prospector', 'satellite_pigeon', 'boss_property_mgmt'],
      boss: 'boss_moonlord', clearTitle: 'Friend of Rabbits',
      stageNames: ['Picket at the Crater', 'The Dust Settles (It Doesn\'t)', 'Tides Turn', 'The LLC Responds', 'MANAGEMENT MANIFESTS', 'Escrow on the Dark Side', 'The Deposit Dispute', 'THE MOONLORD\'S LAST NOTICE'],
      rewardTableId: 'rt_moon_strike', window: ['2026-10-08T00:00:00Z', '2026-10-22T00:00:00Z'],
      rewardTable: [
        { itemId: 'ricecake_token', count: 15, weight: 50 }, { itemId: 'gold', count: 4000, weight: 22 },
        { itemId: 'gems', count: 25, weight: 18 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_mall_madness', name: 'Midnight Mall Madness', kind: 'eventChapter',
      desc: 'One night a year, the Enchanted Mall holds a sale. Everything must go. Including shoppers.',
      theme: 'mall_event', tokenId: 'giftcard_token', stageCount: 6, scale: 1.4, bossScale: 1.3,
      enemyPool: ['kiosk_goblin', 'escalator_serpent', 'perfume_banshee', 'pretzel_elemental', 'mannequin_stalker', 'fountain_nymph', 'boss_food_court'],
      boss: 'boss_mall_heart', clearTitle: 'Doorbuster',
      stageNames: ['Doors Open (RUN)', 'The Sample Stampede', 'Kiosk Krossfire', 'FOOD COURT FRENZY', 'The Clearance Labyrinth', 'THE ANCHOR\'S MIDNIGHT SALE'],
      rewardTableId: 'rt_mall', window: ['2026-11-27T00:00:00Z', '2026-12-04T00:00:00Z'],
      rewardTable: [
        { itemId: 'giftcard_token', count: 12, weight: 55 }, { itemId: 'gold', count: 5000, weight: 25 },
        { itemId: 'gems', count: 30, weight: 12 }, { itemId: 'radiant_core', count: 1, weight: 8 } ] },
    { id: 'ev_gym_trial', name: 'Free Trial at the Astral Gym', kind: 'eventChapter',
      desc: 'Seven days free. Cancel anytime. ("Anytime" not available in your dimension.)',
      theme: 'gym_event', tokenId: 'rep_token', stageCount: 7, scale: 2.0, bossScale: 1.5,
      enemyPool: ['star_spotter', 'nebula_lifter', 'cardio_comet', 'yoga_void', 'protein_ooze', 'mirror_wall', 'boss_front_desk'],
      boss: 'boss_gainz_titan', clearTitle: 'Swole Adjacent',
      stageNames: ['Day One: Optimism', 'Day Two: Regret', 'Day Three: The Void Stretches YOU', 'Day Four: Cardio Comet Chase', 'DAY FIVE: FRONT DESK FRACAS', 'Day Six: Mirror Match', 'DAY SEVEN: ARM DAY ETERNAL'],
      rewardTableId: 'rt_gym', window: ['2027-01-02T00:00:00Z', '2027-01-16T00:00:00Z'],
      rewardTable: [
        { itemId: 'rep_token', count: 15, weight: 50 }, { itemId: 'gold', count: 6000, weight: 22 },
        { itemId: 'gems', count: 30, weight: 18 }, { itemId: 'radiant_core', count: 2, weight: 10 } ] },
    { id: 'ev_snail_derby', name: 'The Grand Snail Derby', kind: 'eventChapter',
      desc: 'The meadow\'s deceptively fast snails hold their annual race. Betting is legal. Survival is optional.',
      theme: 'derby_event', tokenId: 'derby_ticket', stageCount: 5, scale: 1.2, bossScale: 2.2,
      enemyPool: ['meadow_snail', 'slime_green', 'slime_red', 'slime_blue', 'hr_butterfly'],
      boss: 'meadow_snail', clearTitle: 'Photo Finish',
      stageNames: ['Qualifying Laps', 'The Slippery Straightaway', 'Hairpin at Half Speed', 'The Final Furlong (Eventually)', 'THE CHAMPION SNAIL'],
      rewardTableId: 'rt_derby', window: ['2026-09-05T00:00:00Z', '2026-09-12T00:00:00Z'],
      rewardTable: [
        { itemId: 'derby_ticket', count: 10, weight: 60 }, { itemId: 'gold', count: 2500, weight: 25 },
        { itemId: 'speed_shell', count: 2, weight: 15 } ] },
    { id: 'ev_permit_amnesty', name: 'Permit Amnesty Weekend', kind: 'eventChapter',
      desc: 'The Darkwood forgives all expired permits. The catch: you must fight your way to the forgiveness desk.',
      theme: 'amnesty_event', tokenId: 'amnesty_stamp', stageCount: 6, scale: 1.3, bossScale: 1.2,
      enemyPool: ['treant_clerk', 'permit_sprite', 'bramble_lawyer', 'owl_auditor', 'stamp_beetle', 'file_fungus', 'boss_ranger_doreen'],
      boss: 'boss_barkimedes', clearTitle: 'Fully Permitted',
      stageNames: ['The Forgiveness Queue', 'Amnesty Antechamber', 'The Waived Fees Wilds', 'DOREEN\'S DOUBLE SHIFT', 'The Final Form', 'BARKIMEDES SIGNS OFF'],
      rewardTableId: 'rt_amnesty', window: ['2026-12-05T00:00:00Z', '2026-12-12T00:00:00Z'],
      rewardTable: [
        { itemId: 'amnesty_stamp', count: 12, weight: 55 }, { itemId: 'gold', count: 3500, weight: 25 },
        { itemId: 'gems', count: 20, weight: 20 } ] },

    // ------------------------- Material dungeons --------------------------
    { id: 'ev_weekly_ore', name: 'Mount Grumble Ore Runs', kind: 'materialDungeon',
      desc: 'The dwarves (now fairly paid) open the mines on weekends. Ore for everyone who survives the goats.',
      theme: 'ore_dungeon', stageCount: 3, scale: 1.2,
      enemyPool: ['picket_dwarf', 'forge_golem', 'coal_bat', 'grumble_goat'],
      boss: 'forge_golem', recurrence: 'weekly', weekday: 0,
      stageNames: ['Surface Seams', 'The Middle Shafts', 'THE MOTHERLODE'],
      rewardTableId: 'rt_ore',
      rewardTable: [
        { itemId: 'grumble_ore', count: 5, weight: 60 }, { itemId: 'gold', count: 8000, weight: 30 },
        { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_daily_skillbooks', name: 'The Library After Hours', kind: 'materialDungeon',
      desc: 'Goth Librarian Morticia leaves the skill-tome wing unlocked nightly. This is either kindness or a trap.',
      theme: 'library_dungeon', stageCount: 3, scale: 1.5,
      enemyPool: ['queue_skeleton', 'ticket_ghoul', 'form_mummy', 'counter_wight'],
      boss: 'boss_registrar', recurrence: 'daily',
      stageNames: ['The Quiet Section', 'The Quieter Section', 'SILENCE, ENFORCED'],
      rewardTableId: 'rt_skillbooks',
      rewardTable: [
        { itemId: 'skill_tome', count: 3, weight: 60 }, { itemId: 'gold', count: 6000, weight: 30 },
        { itemId: 'gems', count: 15, weight: 10 } ] },

    // -------------------------- Awakening stages --------------------------
    { id: 'ev_awakening_advanced', name: 'The Radiant Core: Deep Custody', kind: 'awakeningStage',
      desc: 'The custodians\' inner sanctum. More cores, more concern, more mop-based violence.',
      theme: 'sanctum_deep', stageCount: 3, scale: 2.2,
      enemyPool: ['core_golem', 'sentinel_fire', 'sentinel_water', 'sentinel_dark'],
      boss: 'sentinel_dark', recurrence: 'weekly', weekday: 5,
      stageNames: ['The Buffed Floors', 'Supply Closet of Secrets', 'THE DEEP CLEAN'],
      rewardTableId: 'rt_awakening_deep',
      rewardTable: [
        { itemId: 'radiant_core', count: 2, weight: 60 }, { itemId: 'radiant_core', count: 4, weight: 30 },
        { itemId: 'radiant_core', count: 8, weight: 10 } ] },

    // -------------------------- Challenge towers --------------------------
    { id: 'ev_tower_spreadsheet', name: 'The Tower of Tabs', kind: 'challengeTower',
      desc: 'Ten sheets. Each tab worse than the last. The final tab has been hidden since creation.',
      theme: 'tab_tower', stageCount: 10, scale: 1.8,
      enemyPool: ['cell_sprite', 'merge_horror', 'circular_ref', 'vlookup_hound', 'macro_gremlin', 'div_zero_specter', 'boss_pivot_dragon', 'boss_autosave'],
      boss: 'boss_formula_one', clearTitle: 'Power User',
      stageNames: ['Sheet1', 'Sheet1 (2)', 'Sheet1 (2) copy', 'Sheet1 (2) copy FINAL', 'PIVOT POINT', 'Sheet_old_DO_NOT_USE', 'The Hidden Tab', 'Untitled Spreadsheet', 'DID YOU SAVE?', 'THE FORMULA BAR'],
      rewardTableId: 'rt_tab_tower',
      rewardTable: [
        { itemId: 'gems', count: 30, weight: 55 }, { itemId: 'gems', count: 60, weight: 30 },
        { itemId: 'radiant_core', count: 2, weight: 15 } ] },
    { id: 'ev_tower_hold', name: 'The Tower of Eternal Hold', kind: 'challengeTower',
      desc: 'Ten floors of Customer Service Hell\'s finest. The elevator music is a boss mechanic.',
      theme: 'hold_tower', stageCount: 10, scale: 1.9,
      enemyPool: ['headset_imp', 'ticket_hydra', 'survey_succubus', 'chatbot_golem', 'refund_wraith', 'warranty_demon', 'boss_tier9_shark', 'boss_kpi_beast'],
      boss: 'boss_complaints_prince', clearTitle: 'Fully Resolved',
      stageNames: ['Your Call Matters (Floor 1)', 'Position In Queue: 9', 'Position In Queue: 8', 'Position In Queue: 8 (Again)', 'TIER 9 CHECKPOINT', 'The Survey Gauntlet', 'Deflection Deck', 'The Churn Floor', 'KPI PENTHOUSE', 'THE PRINCE\'S BACKLOG'],
      rewardTableId: 'rt_hold_tower',
      rewardTable: [
        { itemId: 'gems', count: 35, weight: 55 }, { itemId: 'gems', count: 70, weight: 30 },
        { itemId: 'radiant_core', count: 2, weight: 15 } ] },

    // ----------------------------- Boss rushes ----------------------------
    { id: 'ev_bossrush_sovereigns', name: 'Boss Rush: Sovereigns of Silliness', kind: 'bossRush',
      desc: 'The Hold Queen, the Dead Letter King, the Moonlord, and the Grand Gateau. Royalty, rapid-fire.',
      theme: 'sovereign_rush', stageCount: 4, scale: 1.4, bossScale: 1.4,
      enemyPool: ['boss_hold_queen', 'boss_dead_letter', 'boss_moonlord'],
      boss: 'boss_grand_gateau', recurrence: 'weekly', weekday: 6,
      stageNames: ['THE HOLD QUEEN', 'THE DEAD LETTER KING', 'THE MOONLORD', 'THE GRAND GATEAU'],
      rewardTableId: 'rt_sovereign_rush',
      rewardTable: [
        { itemId: 'gems', count: 50, weight: 50 }, { itemId: 'radiant_core', count: 2, weight: 35 },
        { itemId: 'crown_fragment', count: 1, weight: 15 } ] },
    { id: 'ev_bossrush_cosmic', name: 'Boss Rush: The Cosmic Escalation', kind: 'bossRush',
      desc: 'The endgame bosses, back to back to back. For heroes whose quarterly numbers are IMMACULATE.',
      theme: 'cosmic_rush', stageCount: 4, scale: 1.2, bossScale: 1.2,
      enemyPool: ['boss_membership', 'boss_undersecretary', 'boss_formula_one'],
      boss: 'boss_ceo_everything', clearTitle: 'Cosmically Reviewed',
      stageNames: ['THE CONTRACT', 'THE UNDER-UNDER-SECRETARY', 'THE FIRST FORMULA', 'THE CEO OF EVERYTHING'],
      rewardTableId: 'rt_cosmic_rush',
      rewardTable: [
        { itemId: 'gems', count: 100, weight: 45 }, { itemId: 'radiant_core', count: 3, weight: 35 },
        { itemId: 'executive_seal', count: 1, weight: 20 } ] },
  ],
};
