// Generated event configurations. Enemy pools reference ids from the
// hand-authored enemy files and the generated chapter enemy files.
module.exports = {
  list: [
    // --------------------------- Event chapters ---------------------------
    { id: 'ev_pastry_uprising', name: 'The Pastry Uprising', kind: 'eventChapter',
      desc: 'The Great Dessert rises. Literally. Someone left the proofing spell on overnight.',
      theme: 'dessert_event', tokenId: 'sprinkle_token', stageCount: 8, scale: 1.1, bossScale: 1.2,
      enemyPool: ['rogue_scone', 'custard_elemental', 'churro_cactus', 'gelato_golem', 'biscotti_bandit', 'meringue_wisp', 'boss_tiramisu'],
      boss: 'boss_grand_gateau', clearTitle: 'Cake Appreciator',
      stageNames: ['The Dough Also Rises', 'Crust Uprising', 'Sconehenge', 'The Filling Front', 'TIRAMISU STRIKES BACK', 'Glaze of Glory', 'The Icing Line', 'GATEAU: ROUND TWO'],
      rewardTableId: 'rt_pastry', window: ['2026-09-10T00:00:00Z', '2026-09-24T00:00:00Z'],
      rewardTable: [
        { itemId: 'sprinkle_token', count: 15, weight: 50 }, { itemId: 'gold', count: 3000, weight: 25 },
        { itemId: 'gems', count: 20, weight: 15 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_moon_rent_strike', name: 'The Moon Rent Strike', kind: 'eventChapter',
      desc: 'Before the revolution, there was the rent strike. Stand with the rabbits.',
      theme: 'moon_event', tokenId: 'ricecake_token', stageCount: 8, scale: 1.6, bossScale: 1.4,
      enemyPool: ['moon_rabbit', 'crater_hermit', 'dust_bunny', 'tide_manager', 'cheese_prospector', 'satellite_pigeon', 'boss_property_mgmt'],
      boss: 'boss_moonlord', clearTitle: 'Friend of Rabbits',
      stageNames: ['Picket at the Crater', 'The Dust Settles (It Doesn\'t)', 'Tides Turn', 'The LLC Responds', 'MANAGEMENT MANIFESTS', 'Escrow on the Dark Side', 'The Deposit Dispute', 'THE MOONLORD\'S LAST NOTICE'],
      rewardTableId: 'rt_moon_strike', window: ['2026-10-08T00:00:00Z', '2026-10-22T00:00:00Z'],
      rewardTable: [
        { itemId: 'ricecake_token', count: 15, weight: 50 }, { itemId: 'gold', count: 4000, weight: 22 },
        { itemId: 'gems', count: 25, weight: 18 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_mall_madness', name: 'Midnight Mall Madness', kind: 'eventChapter',
      desc: 'One night a year, the Enchanted Mall holds a sale. Everything must go. Including shoppers.',
      theme: 'mall_event', tokenId: 'giftcard_token', stageCount: 6, scale: 1.4, bossScale: 1.3,
      enemyPool: ['kiosk_goblin', 'escalator_serpent', 'perfume_banshee', 'pretzel_elemental', 'mannequin_stalker', 'fountain_nymph', 'boss_food_court'],
      boss: 'boss_mall_heart', clearTitle: 'Doorbuster',
      stageNames: ['Doors Open (RUN)', 'The Sample Stampede', 'Kiosk Krossfire', 'FOOD COURT FRENZY', 'The Clearance Labyrinth', 'THE ANCHOR\'S MIDNIGHT SALE'],
      rewardTableId: 'rt_mall', window: ['2026-11-27T00:00:00Z', '2026-12-04T00:00:00Z'],
      rewardTable: [
        { itemId: 'giftcard_token', count: 12, weight: 55 }, { itemId: 'gold', count: 5000, weight: 25 },
        { itemId: 'gems', count: 30, weight: 12 }, { itemId: 'radiant_core', count: 1, weight: 8 } ] },
    { id: 'ev_gym_trial', name: 'Free Trial at the Astral Gym', kind: 'eventChapter',
      desc: 'Seven days free. Cancel anytime. ("Anytime" not available in your dimension.)',
      theme: 'gym_event', tokenId: 'rep_token', stageCount: 7, scale: 2.0, bossScale: 1.5,
      enemyPool: ['star_spotter', 'nebula_lifter', 'cardio_comet', 'yoga_void', 'protein_ooze', 'mirror_wall', 'boss_front_desk'],
      boss: 'boss_gainz_titan', clearTitle: 'Swole Adjacent',
      stageNames: ['Day One: Optimism', 'Day Two: Regret', 'Day Three: The Void Stretches YOU', 'Day Four: Cardio Comet Chase', 'DAY FIVE: FRONT DESK FRACAS', 'Day Six: Mirror Match', 'DAY SEVEN: ARM DAY ETERNAL'],
      rewardTableId: 'rt_gym', window: ['2027-01-02T00:00:00Z', '2027-01-16T00:00:00Z'],
      rewardTable: [
        { itemId: 'rep_token', count: 15, weight: 50 }, { itemId: 'gold', count: 6000, weight: 22 },
        { itemId: 'gems', count: 30, weight: 18 }, { itemId: 'radiant_core', count: 2, weight: 10 } ] },
    { id: 'ev_snail_derby', name: 'The Grand Snail Derby', kind: 'eventChapter',
      desc: 'The meadow\'s deceptively fast snails hold their annual race. Betting is legal. Survival is optional.',
      theme: 'derby_event', tokenId: 'derby_ticket', stageCount: 5, scale: 1.2, bossScale: 2.2,
      enemyPool: ['meadow_snail', 'slime_green', 'slime_red', 'slime_blue', 'hr_butterfly'],
      boss: 'meadow_snail', clearTitle: 'Photo Finish',
      stageNames: ['Qualifying Laps', 'The Slippery Straightaway', 'Hairpin at Half Speed', 'The Final Furlong (Eventually)', 'THE CHAMPION SNAIL'],
      rewardTableId: 'rt_derby', window: ['2026-09-05T00:00:00Z', '2026-09-12T00:00:00Z'],
      rewardTable: [
        { itemId: 'derby_ticket', count: 10, weight: 60 }, { itemId: 'gold', count: 2500, weight: 25 },
        { itemId: 'speed_shell', count: 2, weight: 15 } ] },
    { id: 'ev_permit_amnesty', name: 'Permit Amnesty Weekend', kind: 'eventChapter',
      desc: 'The Darkwood forgives all expired permits. The catch: you must fight your way to the forgiveness desk.',
      theme: 'amnesty_event', tokenId: 'amnesty_stamp', stageCount: 6, scale: 1.3, bossScale: 1.2,
      enemyPool: ['treant_clerk', 'permit_sprite', 'bramble_lawyer', 'owl_auditor', 'stamp_beetle', 'file_fungus', 'boss_ranger_doreen'],
      boss: 'boss_barkimedes', clearTitle: 'Fully Permitted',
      stageNames: ['The Forgiveness Queue', 'Amnesty Antechamber', 'The Waived Fees Wilds', 'DOREEN\'S DOUBLE SHIFT', 'The Final Form', 'BARKIMEDES SIGNS OFF'],
      rewardTableId: 'rt_amnesty', window: ['2026-12-05T00:00:00Z', '2026-12-12T00:00:00Z'],
      rewardTable: [
        { itemId: 'amnesty_stamp', count: 12, weight: 55 }, { itemId: 'gold', count: 3500, weight: 25 },
        { itemId: 'gems', count: 20, weight: 20 } ] },

    // ------------------------- Material dungeons --------------------------
    { id: 'ev_weekly_ore', name: 'Mount Grumble Ore Runs', kind: 'materialDungeon',
      desc: 'The dwarves (now fairly paid) open the mines on weekends. Ore for everyone who survives the goats.',
      theme: 'ore_dungeon', stageCount: 3, scale: 1.2,
      enemyPool: ['picket_dwarf', 'forge_golem', 'coal_bat', 'grumble_goat'],
      boss: 'forge_golem', recurrence: 'weekly', weekday: 0,
      stageNames: ['Surface Seams', 'The Middle Shafts', 'THE MOTHERLODE'],
      rewardTableId: 'rt_ore',
      rewardTable: [
        { itemId: 'grumble_ore', count: 5, weight: 60 }, { itemId: 'gold', count: 8000, weight: 30 },
        { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_daily_skillbooks', name: 'The Library After Hours', kind: 'materialDungeon',
      desc: 'Goth Librarian Morticia leaves the skill-tome wing unlocked nightly. This is either kindness or a trap.',
      theme: 'library_dungeon', stageCount: 3, scale: 1.5,
      enemyPool: ['queue_skeleton', 'ticket_ghoul', 'form_mummy', 'counter_wight'],
      boss: 'boss_registrar', recurrence: 'daily',
      stageNames: ['The Quiet Section', 'The Quieter Section', 'SILENCE, ENFORCED'],
      rewardTableId: 'rt_skillbooks',
      rewardTable: [
        { itemId: 'skill_tome', count: 3, weight: 60 }, { itemId: 'gold', count: 6000, weight: 30 },
        { itemId: 'gems', count: 15, weight: 10 } ] },

    // -------------------------- Awakening stages --------------------------
    { id: 'ev_awakening_advanced', name: 'The Radiant Core: Deep Custody', kind: 'awakeningStage',
      desc: 'The custodians\' inner sanctum. More cores, more concern, more mop-based violence.',
      theme: 'sanctum_deep', stageCount: 3, scale: 2.2,
      enemyPool: ['core_golem', 'sentinel_fire', 'sentinel_water', 'sentinel_dark'],
      boss: 'sentinel_dark', recurrence: 'weekly', weekday: 5,
      stageNames: ['The Buffed Floors', 'Supply Closet of Secrets', 'THE DEEP CLEAN'],
      rewardTableId: 'rt_awakening_deep',
      rewardTable: [
        { itemId: 'radiant_core', count: 2, weight: 60 }, { itemId: 'radiant_core', count: 4, weight: 30 },
        { itemId: 'radiant_core', count: 8, weight: 10 } ] },

    // -------------------------- Challenge towers --------------------------
    { id: 'ev_tower_spreadsheet', name: 'The Tower of Tabs', kind: 'challengeTower',
      desc: 'Ten sheets. Each tab worse than the last. The final tab has been hidden since creation.',
      theme: 'tab_tower', stageCount: 10, scale: 1.8,
      enemyPool: ['cell_sprite', 'merge_horror', 'circular_ref', 'vlookup_hound', 'macro_gremlin', 'div_zero_specter', 'boss_pivot_dragon', 'boss_autosave'],
      boss: 'boss_formula_one', clearTitle: 'Power User',
      stageNames: ['Sheet1', 'Sheet1 (2)', 'Sheet1 (2) copy', 'Sheet1 (2) copy FINAL', 'PIVOT POINT', 'Sheet_old_DO_NOT_USE', 'The Hidden Tab', 'Untitled Spreadsheet', 'DID YOU SAVE?', 'THE FORMULA BAR'],
      rewardTableId: 'rt_tab_tower',
      rewardTable: [
        { itemId: 'gems', count: 30, weight: 55 }, { itemId: 'gems', count: 60, weight: 30 },
        { itemId: 'radiant_core', count: 2, weight: 15 } ] },
    { id: 'ev_tower_hold', name: 'The Tower of Eternal Hold', kind: 'challengeTower',
      desc: 'Ten floors of Customer Service Hell\'s finest. The elevator music is a boss mechanic.',
      theme: 'hold_tower', stageCount: 10, scale: 1.9,
      enemyPool: ['headset_imp', 'ticket_hydra', 'survey_succubus', 'chatbot_golem', 'refund_wraith', 'warranty_demon', 'boss_tier9_shark', 'boss_kpi_beast'],
      boss: 'boss_complaints_prince', clearTitle: 'Fully Resolved',
      stageNames: ['Your Call Matters (Floor 1)', 'Position In Queue: 9', 'Position In Queue: 8', 'Position In Queue: 8 (Again)', 'TIER 9 CHECKPOINT', 'The Survey Gauntlet', 'Deflection Deck', 'The Churn Floor', 'KPI PENTHOUSE', 'THE PRINCE\'S BACKLOG'],
      rewardTableId: 'rt_hold_tower',
      rewardTable: [
        { itemId: 'gems', count: 35, weight: 55 }, { itemId: 'gems', count: 70, weight: 30 },
        { itemId: 'radiant_core', count: 2, weight: 15 } ] },

    // ----------------------------- Boss rushes ----------------------------
    { id: 'ev_bossrush_sovereigns', name: 'Boss Rush: Sovereigns of Silliness', kind: 'bossRush',
      desc: 'The Hold Queen, the Dead Letter King, the Moonlord, and the Grand Gateau. Royalty, rapid-fire.',
      theme: 'sovereign_rush', stageCount: 4, scale: 1.4, bossScale: 1.4,
      enemyPool: ['boss_hold_queen', 'boss_dead_letter', 'boss_moonlord'],
      boss: 'boss_grand_gateau', recurrence: 'weekly', weekday: 6,
      stageNames: ['THE HOLD QUEEN', 'THE DEAD LETTER KING', 'THE MOONLORD', 'THE GRAND GATEAU'],
      rewardTableId: 'rt_sovereign_rush',
      rewardTable: [
        { itemId: 'gems', count: 50, weight: 50 }, { itemId: 'radiant_core', count: 2, weight: 35 },
        { itemId: 'crown_fragment', count: 1, weight: 15 } ] },
    // ------------------------ Story & festival events ---------------------
    { id: 'ev_lighthouse_shift', name: 'The Lighthouse Keeper\'s Last Shift', kind: 'eventChapter',
      desc: 'A quiet story about Lampwick Louie, the freelance lighthouse, and the one storm he never talks about.',
      theme: 'lighthouse_event', tokenId: 'wax_blob', stageCount: 6, scale: 1.3, bossScale: 1.3,
      enemyPool: ['storm_courier', 'hold_jelly', 'parcel_pigeon', 'tape_gull', 'phone_eel'],
      boss: 'boss_thunderhead', clearTitle: 'Keeper of the Light',
      stageNames: ['The Dark Coast', 'Letters in the Squall', 'The Old Route', 'What the Storm Took', 'The Light Goes Out', 'ONE LAST SHIFT'],
      rewardTableId: 'rt_lighthouse',
      dialogue: [
        { id: 'evlh_s01', lines: [
          { speaker: '', portrait: '', side: 'left', text: 'A coast with no lighthouse. Louie left this posting years ago. He never says why.' },
          { speaker: 'Lampwick Louie', portrait: 'char_light_louie', side: 'right', text: 'Forty years I lit this water. Then one night the storm was faster than my wick. A mail ship went down. Every letter aboard... lost.' },
          { speaker: 'Hero', portrait: 'npc_hero', side: 'left', text: 'The Dead Letter King released everything. Louie... some of those letters might have made it after all.' },
          { speaker: 'Lampwick Louie', portrait: 'char_light_louie', side: 'right', text: '...then light me up, hero. One last shift. Let\'s go find out.' } ] },
        { id: 'evlh_s06_after', lines: [
          { speaker: '', portrait: '', side: 'left', text: 'The storm clears. On the rocks: a mailbag, sea-worn but sealed. Postmarked the night the light went out.' },
          { speaker: 'Lampwick Louie', portrait: 'char_light_louie', side: 'right', text: 'They wrote back. All those years... the ship\'s crew wrote back. "The light held long enough. We made the far shore. Thank you, keeper."' },
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: '...I\'m not crying. It\'s sea spray. It\'s EMOTIONAL sea spray.' },
          { speaker: 'Lampwick Louie', portrait: 'char_light_louie', side: 'right', text: 'Freelance rates apply from tomorrow. Tonight, the light\'s on the house.' } ] } ],
      stageDialogue: { 1: { before: 'evlh_s01' }, 6: { after: 'evlh_s06_after' } },
      window: ['2026-11-05T00:00:00Z', '2026-11-19T00:00:00Z'],
      rewardTable: [
        { itemId: 'wax_blob', count: 10, weight: 45 }, { itemId: 'dawn_core', count: 1, weight: 30 },
        { itemId: 'gems', count: 25, weight: 25 } ] },
    { id: 'ev_warm_rock_day', name: 'Warm Rock Appreciation Day', kind: 'eventChapter',
      desc: 'The kingdom\'s official holiday for its most beloved rock. The Concept of Monday tries to cancel it.',
      theme: 'rockday_event', tokenId: 'meadow_clover', stageCount: 5, scale: 1.8, bossScale: 0.9,
      enemyPool: ['bee_swarm', 'hr_butterfly', 'clipboard_goblin', 'meadow_wolf'],
      boss: 'boss_monday', clearTitle: 'Friend of Rock',
      stageNames: ['Festival Setup', 'The Warmth Parade', 'Uninvited Paperwork', 'Monday Approaches', 'DEFEND THE HOLIDAY'],
      rewardTableId: 'rt_rockday',
      dialogue: [
        { id: 'evwr_s01', lines: [
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Warm Rock Appreciation Day! The kingdom\'s first holiday ratified by unanimous vote, three abstentions (all pebbles, jealous).' },
          { speaker: 'Hero', portrait: 'npc_hero', side: 'left', text: 'What are the festival activities?' },
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Holding the rock. Appreciating the rock. There is also a raffle. The prize is proximity to the rock.' } ] },
        { id: 'evwr_s05_after', lines: [
          { speaker: '', portrait: '', side: 'left', text: 'Monday retreats, defeated by a holiday it could not cancel. The crowd holds Warm Rock aloft. Warm Rock radiates quiet, perfect warmth.' },
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Somewhere, Spooky Pebble is watching. Maybe next year, cousin. Maybe next year.' } ] } ],
      stageDialogue: { 1: { before: 'evwr_s01' }, 5: { after: 'evwr_s05_after' } },
      recurrence: 'weekly', weekday: 4,
      rewardTable: [
        { itemId: 'meadow_clover', count: 10, weight: 50 }, { itemId: 'gold', count: 3000, weight: 30 },
        { itemId: 'gems', count: 20, weight: 20 } ] },
    { id: 'ev_onboarding', name: 'Adventurer Onboarding (Paid Training)', kind: 'eventChapter',
      desc: 'A gentle training course for new heroes: dragging, cascades, hearts, elements and countdowns — with pay.',
      theme: 'training_event', tokenId: 'permit_stub', stageCount: 6, scale: 0.5, bossScale: 0.6,
      enemyPool: ['slime_green', 'slime_red', 'slime_blue', 'meadow_snail'],
      boss: 'boss_slime_dave', clearTitle: 'Fully Onboarded',
      stageNames: ['Lesson 1: The Drag', 'Lesson 2: The Cascade', 'Lesson 3: Hearts', 'Lesson 4: Elements', 'Lesson 5: Countdowns', 'FINAL EXAM: DAVE (SUPERVISED)'],
      rewardTableId: 'rt_onboarding',
      dialogue: [
        { id: 'evob_s01', lines: [
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Welcome to Onboarding! Grab an orb, drag it anywhere — every orb you cross swaps places with it. You have ten seconds per move. Make them count!' },
          { speaker: 'Hero', portrait: 'npc_hero', side: 'left', text: 'Three of the same color in a line. Got it.' },
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'And SEPARATE matches mean SEPARATE attacks! Two Fire matches? Your Fire heroes swing TWICE. It\'s in the handbook. I wrote the handbook.' } ] },
        { id: 'evob_s03', lines: [
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Pink Heart orbs heal your party — match them when your HP dips. And when the board settles, new orbs fall. Chain those cascades for bonus combos!' } ] },
        { id: 'evob_s05', lines: [
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'See the number on the enemy? That\'s its countdown. Every move you finish ticks it down — at zero, it acts! Fire beats Nature, Nature beats Water, Water beats Fire. Light and Dark? They beat each OTHER.' },
          { speaker: 'Hero', portrait: 'npc_hero', side: 'left', text: 'And skills charge from matching my element.' },
          { speaker: 'Pip', portrait: 'npc_pip', side: 'left', text: 'Look at you! Tap a glowing portrait when the skill is READY. Your leader\'s skill is always on — build your team around it!' } ] } ],
      stageDialogue: { 1: { before: 'evob_s01' }, 3: { before: 'evob_s03' }, 5: { before: 'evob_s05' } },
      rewardTable: [
        { itemId: 'permit_stub', count: 5, weight: 40 }, { itemId: 'gems', count: 30, weight: 35 },
        { itemId: 'exp_scroll', count: 3, weight: 25 } ] },

    // --------------------- Weekday element material runs -------------------
    { id: 'ev_monday_embers', name: 'Monday: Ember Core Runs', kind: 'materialDungeon',
      desc: 'Fire Awakening materials, forged fresh every Monday. Monday hates this.',
      theme: 'ember_dungeon', stageCount: 3, scale: 1.4,
      enemyPool: ['ash_slime', 'forge_golem', 'sentinel_fire'], boss: 'sentinel_fire',
      recurrence: 'weekly', weekday: 1,
      stageNames: ['Kindling Run', 'The Bellows Floor', 'THE EMBER VAULT'],
      rewardTableId: 'rt_embers',
      rewardTable: [ { itemId: 'ember_core', count: 1, weight: 60 }, { itemId: 'ember_core', count: 2, weight: 30 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_tuesday_tides', name: 'Tuesday: Tide Core Runs', kind: 'materialDungeon',
      desc: 'Water Awakening materials, drawn at high tide every Tuesday.',
      theme: 'tide_dungeon', stageCount: 3, scale: 1.4,
      enemyPool: ['hold_jelly', 'squid_operator', 'sentinel_water'], boss: 'sentinel_water',
      recurrence: 'weekly', weekday: 2,
      stageNames: ['Shallow Draw', 'The Undertow Floor', 'THE TIDE VAULT'],
      rewardTableId: 'rt_tides',
      rewardTable: [ { itemId: 'tide_core', count: 1, weight: 60 }, { itemId: 'tide_core', count: 2, weight: 30 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_wednesday_blooms', name: 'Wednesday: Bloom Core Runs', kind: 'materialDungeon',
      desc: 'Nature Awakening materials. Harvested mid-week, when the plants least expect it.',
      theme: 'bloom_dungeon', stageCount: 3, scale: 1.4,
      enemyPool: ['treant_clerk', 'bramble_lawyer', 'lawn_ghost'], boss: 'treant_clerk',
      recurrence: 'weekly', weekday: 3,
      stageNames: ['The Seed Row', 'The Overgrowth Floor', 'THE BLOOM VAULT'],
      rewardTableId: 'rt_blooms',
      rewardTable: [ { itemId: 'bloom_core', count: 1, weight: 60 }, { itemId: 'bloom_core', count: 2, weight: 30 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_thursday_dawns', name: 'Thursday: Dawn Core Runs', kind: 'materialDungeon',
      desc: 'Light Awakening materials, gathered at dawn. Thursday dawn, specifically. It\'s brighter. Trust us.',
      theme: 'dawn_dungeon', stageCount: 3, scale: 1.4,
      enemyPool: ['permit_sprite', 'photo_wisp', 'gem_recruiter'], boss: 'core_golem',
      recurrence: 'weekly', weekday: 4,
      stageNames: ['First Light Run', 'The Radiance Floor', 'THE DAWN VAULT'],
      rewardTableId: 'rt_dawns',
      rewardTable: [ { itemId: 'dawn_core', count: 1, weight: 60 }, { itemId: 'dawn_core', count: 2, weight: 30 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_friday_dusks', name: 'Friday: Dusk Core Runs', kind: 'materialDungeon',
      desc: 'Dark Awakening materials, collected after office hours on Fridays. The dark does not do overtime.',
      theme: 'dusk_dungeon', stageCount: 3, scale: 1.4,
      enemyPool: ['coal_bat', 'onboarding_bat', 'sentinel_dark'], boss: 'sentinel_dark',
      recurrence: 'weekly', weekday: 5,
      stageNames: ['Twilight Run', 'The Gloom Floor', 'THE DUSK VAULT'],
      rewardTableId: 'rt_dusks',
      rewardTable: [ { itemId: 'dusk_core', count: 1, weight: 60 }, { itemId: 'dusk_core', count: 2, weight: 30 }, { itemId: 'radiant_core', count: 1, weight: 10 } ] },
    { id: 'ev_weekend_training', name: 'Weekend Training Camp', kind: 'materialDungeon',
      desc: 'EXP scrolls and gold, all weekend. Chad Emberstorm designed the program. There is a lot of cardio.',
      theme: 'training_dungeon', stageCount: 3, scale: 1.6,
      enemyPool: ['grumble_goat', 'gold_golem', 'star_spotter'], boss: 'gold_golem',
      recurrence: 'weekly', weekday: 6,
      stageNames: ['Warmup Circuit', 'The Growth Floor', 'GRADUATION GAUNTLET'],
      rewardTableId: 'rt_training',
      rewardTable: [ { itemId: 'exp_scroll', count: 4, weight: 50 }, { itemId: 'gold', count: 10000, weight: 35 }, { itemId: 'exp_scroll', count: 10, weight: 15 } ] },

    // --------------------------- Rule towers ------------------------------
    { id: 'ev_tower_purity', name: 'The Tower of Purity (Mono-Element)', kind: 'challengeTower',
      desc: 'Ten floors, one rule: bring one element only. The tower checks. The tower ALWAYS checks.',
      theme: 'purity_tower', stageCount: 10, scale: 1.7,
      enemyPool: ['sentinel_fire', 'sentinel_water', 'sentinel_dark', 'core_golem', 'nebula_lifter', 'yoga_void'],
      boss: 'boss_gainz_titan', clearTitle: 'Purist',
      modifiers: { 1: ['mono_element_only'], 2: ['mono_element_only'], 3: ['mono_element_only'], 4: ['mono_element_only'], 5: ['mono_element_only'], 6: ['mono_element_only'], 7: ['mono_element_only'], 8: ['mono_element_only'], 9: ['mono_element_only'], 10: ['mono_element_only', 'combo_shield:3'] },
      stageNames: ['Floor 1: Prove Your Devotion', 'Floor 2: No Mixing', 'Floor 3: The Purity Check', 'Floor 4: Still One Element?', 'Floor 5: Halfway Devotion', 'Floor 6: The Tempting Rainbow', 'Floor 7: Resist', 'Floor 8: Almost Pure', 'Floor 9: The Final Filter', 'FLOOR 10: ABSOLUTE PURITY'],
      rewardTableId: 'rt_purity',
      rewardTable: [ { itemId: 'gems', count: 40, weight: 50 }, { itemId: 'radiant_core', count: 2, weight: 35 }, { itemId: 'spark_essence', count: 20, weight: 15 } ] },
    { id: 'ev_tower_haste', name: 'The Tower of No Time (Speed Rules)', kind: 'challengeTower',
      desc: 'Ten floors with a shortened move timer and no Heart orbs. The tower is late for something.',
      theme: 'haste_tower', stageCount: 10, scale: 1.7,
      enemyPool: ['cardio_comet', 'meadow_snail', 'satellite_pigeon', 'escalator_serpent', 'circular_ref', 'drone_cherub'],
      boss: 'boss_autosave', clearTitle: 'Speedrunner',
      modifiers: { 1: ['move_time_minus:2'], 2: ['move_time_minus:2'], 3: ['move_time_minus:2', 'no_heart_orbs'], 4: ['move_time_minus:2'], 5: ['move_time_minus:3'], 6: ['move_time_minus:3', 'no_heart_orbs'], 7: ['move_time_minus:3'], 8: ['move_time_minus:3', 'no_heart_orbs'], 9: ['move_time_minus:3', 'enemy_haste'], 10: ['move_time_minus:3', 'no_heart_orbs', 'enemy_haste'] },
      stageNames: ['Floor 1: Hurry Up', 'Floor 2: Faster', 'Floor 3: No Healing, No Waiting', 'Floor 4: The Sprint', 'Floor 5: Seven Seconds', 'Floor 6: Tick', 'Floor 7: Tock', 'Floor 8: The Blur', 'Floor 9: Everything Hastens', 'FLOOR 10: DID YOU SAVE? NO TIME'],
      rewardTableId: 'rt_haste',
      rewardTable: [ { itemId: 'gems', count: 40, weight: 50 }, { itemId: 'radiant_core', count: 2, weight: 35 }, { itemId: 'spark_essence', count: 20, weight: 15 } ] },

    { id: 'ev_bossrush_cosmic', name: 'Boss Rush: The Cosmic Escalation', kind: 'bossRush',
      desc: 'The endgame bosses, back to back to back. For heroes whose quarterly numbers are IMMACULATE.',
      theme: 'cosmic_rush', stageCount: 4, scale: 1.2, bossScale: 1.2,
      enemyPool: ['boss_membership', 'boss_undersecretary', 'boss_formula_one'],
      boss: 'boss_ceo_everything', clearTitle: 'Cosmically Reviewed',
      stageNames: ['THE CONTRACT', 'THE UNDER-UNDER-SECRETARY', 'THE FIRST FORMULA', 'THE CEO OF EVERYTHING'],
      rewardTableId: 'rt_cosmic_rush',
      rewardTable: [
        { itemId: 'gems', count: 100, weight: 45 }, { itemId: 'radiant_core', count: 3, weight: 35 },
        { itemId: 'executive_seal', count: 1, weight: 20 } ] },
  ],
};
