using System;
using System.Collections.Generic;

namespace PuzzleGame.Presentation
{
    // ---------------------------------------------------------------------
    // Integration seams between presentation and core systems.
    //
    // Codex owns the authoritative implementations (board, combat, gacha
    // probability, economy, scheduler, save). Presentation code must only
    // talk to these interfaces. Mock implementations live in
    // Integration/Mock and exist purely so the presentation layer can run
    // and be reviewed before core lands. Binding real systems should only
    // require registering different implementations in PresentationServices.
    // ---------------------------------------------------------------------

    /// <summary>Board + battle state stream consumed by the HUD/VFX.</summary>
    public interface IBattleEventSource
    {
        BattleHudState State { get; }

        /// <summary>Current 6x5 board; [col, row], row 0 at bottom.</summary>
        OrbColor[,] Board { get; }
        OrbStateFlags[,] BoardStates { get; }

        event Action BoardChanged;
        event Action<MatchEvent> MatchResolved;
        event Action<AttackEvent> AttackPerformed;
        event Action<HealEvent> Healed;
        event Action<int> ComboChanged;
        event Action<EnemyActionEvent> EnemyActed;
        event Action<int> EnemyCountdownChanged;      // enemy index
        event Action<int> EnemyDefeated;              // enemy index
        event Action<SkillCastEvent> SkillCast;
        event Action StateChanged;                    // party hp / charges / wave changed
        event Action<BattleEndEvent> BattleEnded;

        /// <summary>Player started dragging the orb at the given cell.</summary>
        void BeginMove(BoardCell cell);
        /// <summary>Dragged orb entered a new cell (core performs the swap).</summary>
        void DragTo(BoardCell cell);
        /// <summary>Player released (or the 10s timer expired).</summary>
        void EndMove();
        /// <summary>Player tapped a ready active skill.</summary>
        void CastSkill(int partySlot);
    }

    /// <summary>Gacha/summon seam. RNG and guarantees are resolved by core.</summary>
    public interface ISummonSource
    {
        IReadOnlyList<BannerVm> GetBanners();
        BannerVm GetBanner(string bannerId);

        /// <summary>
        /// Confirm and pay for a summon. Results are fully pre-generated by
        /// core gacha logic; presentation only reveals them.
        /// Returns null if the summon could not be performed (insufficient
        /// gems, consumed step, expired banner).
        /// </summary>
        SummonSession RequestSummon(string bannerId, bool multi);

        /// <summary>Gather-In/Step-Up: pull the banner's current step.</summary>
        SummonSession RequestStepSummon(string bannerId);
    }

    /// <summary>Owned roster + progression actions.</summary>
    public interface IRosterSource
    {
        IReadOnlyList<CharacterView> GetOwned();
        CharacterView GetOwned(string characterId);

        event Action RosterChanged;

        /// <summary>Attempt a level up; returns false if unaffordable/capped.</summary>
        bool TryLevelUp(string characterId, int levels);
        /// <summary>Attempt 6-star Awakening (thresholds + materials, never duplicates).</summary>
        bool TryAwaken(string characterId);
        /// <summary>Whether awakening requirements are currently met, with display lines.</summary>
        bool GetAwakenRequirements(string characterId, List<string> outLines);
    }

    /// <summary>Currency balances for HUD/summon displays.</summary>
    public interface IEconomySource
    {
        long GetBalance(CurrencyId currency);
        event Action BalancesChanged;
    }

    /// <summary>
    /// Rotating-content seam. Presentation reads what is active from the
    /// core scheduler and NEVER computes date logic itself.
    /// </summary>
    public interface IScheduleSource
    {
        IReadOnlyList<ScheduledContentVm> GetActiveContent();
        IReadOnlyList<ScheduledContentVm> GetUpcomingContent(int maxCount);
        DateTime NowUtc { get; }
    }

    /// <summary>
    /// Creates a battle event source for a stage. The real implementation
    /// builds a core-driven battle; the demo installs a mock simulator.
    /// </summary>
    public interface IBattleFactory
    {
        /// <summary>
        /// Returns the battle source plus the per-frame pump the battle
        /// screen must tick.
        /// </summary>
        IBattleEventSource Create(Content.ChapterDto chapter, Content.StageDto stage, out Action<float> pump);
    }

    /// <summary>Static content definitions (characters, stages, dialogue...).</summary>
    public interface IContentLibrary
    {
        CharacterView GetCharacter(string id);
        IReadOnlyList<CharacterView> GetAllCharacters();
        IReadOnlyList<StageSummaryVm> GetChapterStages(int chapterNumber);
        int GetChapterCount();
        string GetChapterTitle(int chapterNumber);
    }
}
