using System;
using System.Collections.Generic;

namespace PuzzleGame.Presentation
{
    // ---------------------------------------------------------------------
    // Read-only view models handed to UI. These are what the presentation
    // layer renders; they are produced by Integration sources (mocks today,
    // adapters over Codex core systems once those land).
    // ---------------------------------------------------------------------

    [Serializable]
    public class SkillView
    {
        public string Name;
        public string Description;
        /// <summary>Current charge (matched-orb progress) toward readiness.</summary>
        public int Charge;
        public int ChargeMax;
        public bool Ready => ChargeMax > 0 && Charge >= ChargeMax;
    }

    [Serializable]
    public class LeaderSkillView
    {
        public string Name;
        public string Description;
    }

    [Serializable]
    public class CharacterView
    {
        public string Id;
        public string DisplayName;
        public string Epithet;              // silly flavor title, e.g. "Licensed Bog Accountant"
        public ElementId Element;
        public int BaseRarity;              // 1..5 stars, pullable
        public bool Awakened;               // 6-star awakened form active
        public int CurrentRarity => Awakened ? 6 : BaseRarity;
        public int Level;
        public int LevelMax;
        public int Hp;
        public int Atk;
        public int Rec;
        public int Ascension;               // duplicate-driven, 0..AscensionCap
        public int AscensionCap = 5;
        public SkillView ActiveSkill;
        public LeaderSkillView LeaderSkill;
        public string PassiveName;
        public string PassiveDescription;
        public List<string> Tags = new List<string>();
        public string ArtRef;               // base art reference key
        public string AwakenedArtRef;       // awakened art reference key
        public string VfxRef;               // base vfx reference key
        public string AwakenedVfxRef;       // awakened vfx reference key
        public string Flavor;               // story blurb

        /// <summary>Art key that should currently be displayed.</summary>
        public string CurrentArtRef => Awakened && !string.IsNullOrEmpty(AwakenedArtRef) ? AwakenedArtRef : ArtRef;
    }

    [Serializable]
    public class EnemyView
    {
        public string Id;
        public string DisplayName;
        public ElementId Element;
        public long HpMax;
        public long Hp;
        public int Countdown;               // board resolutions until it acts
        public int CountdownMax;
        public bool IsBoss;
        public string ArtRef;
        public List<string> ActiveStatuses = new List<string>();   // e.g. "Combo Shield 5", "Enraged"
        public string TelegraphText;        // what it is about to do, if telegraphed
    }

    [Serializable]
    public class PartyMemberView
    {
        public CharacterView Character;
        public bool IsLeader;
        public bool Bound;                  // bind status disables the unit
    }

    /// <summary>Snapshot of everything the battle HUD renders.</summary>
    public class BattleHudState
    {
        public List<PartyMemberView> Party = new List<PartyMemberView>();
        public long PartyHp;
        public long PartyHpMax;
        public List<EnemyView> Enemies = new List<EnemyView>();
        public int Combo;
        public float MoveTimeRemaining;
        public float MoveTimeTotal = 10f;
        public bool Moving;
        public string StageName;
        public int WaveIndex;
        public int WaveCount;
        public int BoardResolutions;        // for the 3-star speed goal display
    }

    // ------------------------------ Summon --------------------------------

    /// <summary>One revealed card in a summon session. RNG already resolved by core.</summary>
    [Serializable]
    public class SummonCardResult
    {
        public string CharacterId;
        public CharacterView Character;
        public bool IsNew;
        /// <summary>Ascension level reached because of this duplicate (0 = not a duplicate gain).</summary>
        public int AscensionAfter;
        public bool AscensionGained;
        /// <summary>Overflow reward granted when the duplicate exceeded max Ascension.</summary>
        public string OverflowReward;
    }

    /// <summary>A confirmed summon whose results were pre-generated by core gacha logic.</summary>
    public class SummonSession
    {
        public string BannerId;
        public BannerVm Banner;
        public List<SummonCardResult> Cards = new List<SummonCardResult>();
        /// <summary>Highest rarity in the pack; drives pack tier presentation/teasing.</summary>
        public int MaxRarity;
        public int GemCost;
        /// <summary>Step index consumed if this was a Gather-In / Step-Up pull.</summary>
        public int StepIndex = -1;
    }

    [Serializable]
    public class BannerStepVm
    {
        public int Index;
        public int GemCost;
        public int PullCount;
        public bool Consumed;
        public string GuaranteeText;        // e.g. "Guaranteed 5★"
    }

    public class BannerVm
    {
        public string Id;
        public string DisplayName;
        public BannerKind Kind;
        public string Description;
        public List<CharacterView> FeaturedUnits = new List<CharacterView>();
        public string RatesText;            // formatted rates/info block from core data
        public int SingleCost = 150;
        public int MultiCost = 1500;
        public int MultiCount = 10;
        public DateTime? EndsAtUtc;         // null = permanent
        public bool Active;
        public string PackArtRef;           // pack art/theme key for the rip presentation
        public string GuaranteeText;
        /// <summary>Gather-In / Step-Up state.</summary>
        public List<BannerStepVm> Steps = new List<BannerStepVm>();
        public int CurrentStep;             // index into Steps
        public int RotationIndex;           // Gather-In rotation number (1-based)
    }

    // ------------------------------ Schedule ------------------------------

    public class ScheduledContentVm
    {
        public string Id;
        public ScheduledContentKind Kind;
        public string DisplayName;
        public string Description;
        public DateTime StartUtc;
        public DateTime EndUtc;
        public bool Permanent;
        public string TargetId;             // banner id / event chapter id / stage list id
        public string ThemeRef;
    }

    // ------------------------------ Stages --------------------------------

    public class StageSummaryVm
    {
        public string Id;
        public string DisplayName;
        public int ChapterNumber;
        public int StageNumber;
        public int StarsEarned;             // 0..3
        public bool Cleared;
        public bool Unlocked;
        public string BossPreview;
    }
}
